api_version = "2026-04"

[[extensions]]
uid = "173af04c-1584-da61-9f00-577342b535eb1a6c5c21"
type = "function"
name = "B2B Catalog Discount"
handle = "b2b-catalog-discount"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"
