api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "b2b-price-transformer"
type = "function"
uid = "ca95c4c2-f6bc-c09a-1a2c-fb27a244c39177702368"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
