api_version = "2026-04"

[[extensions]]
uid = "bcd977c8-5d56-4f1b-ba1f-c7e7c12f7131"
type = "function"
name = "BOGO Bundles"
handle = "bogo-bundles"

  [extensions.build]
  typegen_command = "node --version"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"
