api_version = "2026-04"

[[extensions]]
uid = "55d07ab6-ded1-4a37-9e5e-a4bebaa0b0a2"
type = "function"
name = "BOGO Bundles"
handle = "bogo-bundles"

  [extensions.build]
  typegen_command = "node --version"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"
