# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c19c401d15d011936f4c7db6715514b3"
name = "Dutch Rusk Catalog Manager"
application_url = "https://dutch-rusk-catalog-manager.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,read_products,write_products,read_publications,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dutch-rusk-catalog-manager.onrender.com/api/auth/callback"
]
