api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "b2b-company-required"
type = "function"
uid = "ac527dee-abb7-b7db-58e7-0e27eea9bfee91cc5bf2"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
