query RunInput {
  cart {
    buyerIdentity {
      purchasingCompany {
        company {
          priceListId: metafield(namespace: "custom", key: "catalog_pricelist_id") {
            value
          }
          discountPct: metafield(namespace: "custom", key: "catalog_discount_pct") {
            value
          }
        }
      }
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          fixedPrices: metafield(namespace: "custom", key: "catalog_fixed_prices") {
            value
          }
          standardRetail: metafield(namespace: "custom", key: "standard_retail_price") {
            value
          }
        }
      }
    }
  }
}
