api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "b2b-custom-prices"
type = "function"
uid = "cc405e8a-62e8-dced-4a74-daf715b4b2be3f50c302"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
